(define (problem EC2-test)
	(:domain EC2)
	(:objects
		inst1 inst2 inst3 inst4 inst5 inst6 inst7 inst8 inst9 - instance
		vol1_50 vol2_50 vol3_50 vol4_50 vol5_50 vol6_50
			vol7_50 vol8_50 vol9_50
			vol1_100 vol2_100 vol3_100 vol4_100 vol5_100 vol6_100 - volume
		app_domain opt_oracle app_domain_logs - filesystem
		app1 app2 app3 db1 - application
	)
	(:init
		(vol-attach-to-in inst1 vol1_50)
		(vol-attach-to-in inst2 vol2_50)
		(vol-attach-to-in inst3 vol3_50)
		(vol-attach-to-in inst4 vol4_50)
		(vol-attach-to-in inst5 vol5_50)
		(vol-attach-to-in inst6 vol6_50)
		(vol-attach-to-in inst1 vol1_100)
		(vol-attach-to-in inst2 vol2_100)
		(vol-attach-to-in inst3 vol3_100)
		(vol-attach-to-in inst4 vol4_100)
		(vol-attach-to-in inst5 vol5_100)
		(vol-attach-to-in inst6 vol6_100)
		(vol-attach-to-in inst7 vol7_50)
		(vol-attach-to-in inst8 vol8_50)
		(vol-attach-to-in inst9 vol9_50)
		(fs-create-on-vol vol1_50 app_domain)
		(fs-create-on-vol vol2_50 app_domain)
		(fs-create-on-vol vol3_50 app_domain)
		(fs-create-on-vol vol4_50 app_domain)
		(fs-create-on-vol vol5_50 app_domain)
		(fs-create-on-vol vol6_50 app_domain)
		(fs-create-on-vol vol1_100 app_domain_logs)
		(fs-create-on-vol vol2_100 app_domain_logs)
		(fs-create-on-vol vol3_100 app_domain_logs)
		(fs-create-on-vol vol4_100 app_domain_logs)
		(fs-create-on-vol vol5_100 app_domain_logs)
		(fs-create-on-vol vol6_100 app_domain_logs)
		(fs-create-on-vol vol7_50 opt_oracle)
		(fs-create-on-vol vol8_50 opt_oracle)
		(fs-create-on-vol vol9_50 opt_oracle)
		(app-use-fs app_domain app1)
		(app-use-fs app_domain app2)
		(app-use-fs app_domain app3)
		(app-use-fs app_domain_logs app1)
		(app-use-fs app_domain_logs app2)
		(app-use-fs app_domain_logs app3)
		(app-use-fs opt_oracle db1)
		(app-run-on-in inst1 app1)
		(app-run-on-in inst2 app2)
		(app-run-on-in inst3 app3)
		(app-run-on-in inst4 app1)
		(app-run-on-in inst5 app2)
		(app-run-on-in inst6 app3)
		(app-run-on-in inst7 db1)
		(app-run-on-in inst8 db1)
		(app-run-on-in inst9 db1)
		(startup-order-app db1 app2)
		(startup-order-app app2 app1)
	)
	(:goal
		(and
			(running-app app1 inst1)
			(running-app app2 inst2)
			(running-app app3 inst3)
			(running-app app1 inst4)
			(running-app app2 inst5)
			(running-app app3 inst6)
			(running-app db1 inst7)
			(running-app db1 inst8)
			(running-app db1 inst9)
		)
	)
)
